# DATATYPES AND ATTRIBUTES

In [11]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,4,6],[4,8,9]])
a2

array([[1, 4, 6],
       [4, 8, 9]])

In [5]:
a3 = np.array([[1,4,6],[4,8,9],[7,8,9]])
a3

array([[1, 4, 6],
       [4, 8, 9],
       [7, 8, 9]])

In [6]:
a4= np.array([[[1,4,6],[4,8,9],[7,8,9]],
             [[3,1,8],[5,8,9],[5,3,2]]])
a4

array([[[1, 4, 6],
        [4, 8, 9],
        [7, 8, 9]],

       [[3, 1, 8],
        [5, 8, 9],
        [5, 3, 2]]])

In [7]:
a3.dtype

dtype('int32')

In [8]:
 a1.dtype

dtype('int32')

In [9]:
a2.dtype

dtype('int32')

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(3, 3)

In [13]:
a4.shape

(2, 3, 3)

In [14]:
a3.size

9

In [15]:
a4.size

18

In [16]:
type(a1)

numpy.ndarray

In [17]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  4  6
1  4  8  9

# CREATING NUMPY ARRAYS


In [18]:
np.ones((2,3))    

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
ra = np.random.randint(0,10,(2,3))
ra

array([[0, 1, 7],
       [3, 1, 0]])

In [21]:
ra = np.random.randint(0,10)
ra

8

In [22]:
np.random.seed(99)
ra1 =np.random.randit((3,4))
ra1

AttributeError: module 'numpy.random' has no attribute 'randit'

In [ ]:
a3

In [ ]:
a3[:2,:2]

In [ ]:
a4[:2,:4,:2]

In [ ]:
a5 = np.random.randint(10,size=(2,4,3,6))
a5
# (set ,in 1 set , row, column, )

In [23]:
a3*a3

array([[ 1, 16, 36],
       [16, 64, 81],
       [49, 64, 81]])

In [24]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [37]:
# a2**2
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.square(a2) 
# both will give same


array([[ 1, 16, 36],
       [16, 64, 81]], dtype=int32)

In [30]:
a2/a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
a2//a2

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [32]:
a2%a2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# AGGREGATION

performing same operation on a multiple things

In [47]:
sum (a2) #sum of all eements of a column in one row

# np.mean(a2)
# np.std(a2)
# np.sqrt(np.var(a2))


array([ 5, 12, 15])

In [44]:
np.sum(a2)
# sum of all the elements

32

In [48]:
np.max(a2)

9

In [49]:
a2

array([[1, 4, 6],
       [4, 8, 9]])

In [50]:
np.mean(a2)

5.333333333333333

In [51]:
# variance = the measure of average degree to which eahc number is different from the other numbers


# Reshaping and tranposing

In [53]:
# when can reshape the array to multiply it with other array

In [86]:
a2_reshape =a2.reshape(2,3,1)
a2_reshape
# (number , row , column)

array([[[1],
        [4],
        [6]],

       [[4],
        [8],
        [9]]])

In [87]:
a2_reshape*a3
# (2,1,3)(3,3)
# both should be equal
# OR
# one of them should be one
# (2,3,1)(3,3)

array([[[ 1,  4,  6],
        [16, 32, 36],
        [42, 48, 54]],

       [[ 4, 16, 24],
        [32, 64, 72],
        [63, 72, 81]]])

In [88]:
a2.T

array([[1, 4],
       [4, 8],
       [6, 9]])

In [90]:
a2

array([[1, 4, 6],
       [4, 8, 9]])

In [100]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(2,3))
mat2 = np.random.randint(10 , size= (2,2))
mat1


array([[5, 0, 3],
       [3, 7, 9]])

In [101]:
mat2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 1],
       [6, 7, 7],
       [8, 1, 5]])

In [104]:
np.dot(mat1,mat2.T)
# dot product will give 2*5 when 2*3 and 5*3

array([[ 21,  38,  43,  51,  55],
       [ 62, 115,  89, 130,  76]])

In [103]:
mat1*mat2
# element wise will give error

ValueError: operands could not be broadcast together with shapes (2,3) (5,3) 

In [110]:
mat3 = np.random.randint(10,size=(2,3))
mat3*mat1 
# both 2*3 

array([[15,  0,  0],
       [ 6, 21, 72]])

# Comparison Operators

In [119]:
a1


array([1, 2, 3])

In [117]:
a2

array([[1, 4, 6],
       [4, 8, 9]])

In [122]:
a2 >mat2

# why???????????

ValueError: operands could not be broadcast together with shapes (2,3) (5,3) 

In [124]:
np.sort(mat2)

array([[2, 3, 5],
       [4, 6, 7],
       [1, 8, 8],
       [6, 7, 7],
       [1, 5, 8]])

In [13]:
#*************** x[start:stop:step] ****************#

x= np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements
array([0, 1, 2, 3, 4])
x[5:]  # elements after index 5
array([5, 6, 7, 8, 9])
x[4:7]  # middle sub-array
array([4, 5, 6])
x[::2]  # every other element
array([0, 2, 4, 6, 8])
x[1::2]  # every other element, starting at index 1

x[::-1]  # all elements, reversed
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
x[5::-2]  # reversed every other from index 5
array([5, 3, 1])

# Images into Numpy Array


In [1]:
from matplotlib.image import imread

<img src="panda.png"/>

In [5]:
panda = imread('panda.png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0